// Seti icon data — transcribed from VSCode's default "Seti" icon theme
// (extensions/theme-seti in microsoft/vscode). Derived from Seti UI by
// Jesse Weed (jesseweed/seti-ui), MIT, Copyright (c) 2014 Jesse Weed.

export const ICONS: Record<string, { c: string; color: string }> = {
	"_R_light": { c: "\uE001", color: "#498ba7" },
	"_R": { c: "\uE001", color: "#519aba" },
	"_argdown_light": { c: "\uE003", color: "#498ba7" },
	"_argdown": { c: "\uE003", color: "#519aba" },
	"_asm_light": { c: "\uE004", color: "#b8383d" },
	"_asm": { c: "\uE004", color: "#cc3e44" },
	"_audio_light": { c: "\uE005", color: "#9068b0" },
	"_audio": { c: "\uE005", color: "#a074c4" },
	"_babel_light": { c: "\uE006", color: "#b7b73b" },
	"_babel": { c: "\uE006", color: "#cbcb41" },
	"_bazel_light": { c: "\uE007", color: "#7fae42" },
	"_bazel": { c: "\uE007", color: "#8dc149" },
	"_bazel_1_light": { c: "\uE007", color: "#455155" },
	"_bazel_1": { c: "\uE007", color: "#4d5a5e" },
	"_bicep_light": { c: "\uE008", color: "#498ba7" },
	"_bicep": { c: "\uE008", color: "#519aba" },
	"_bower_light": { c: "\uE009", color: "#cc6d2e" },
	"_bower": { c: "\uE009", color: "#e37933" },
	"_bsl_light": { c: "\uE00A", color: "#b8383d" },
	"_bsl": { c: "\uE00A", color: "#cc3e44" },
	"_c_light": { c: "\uE00C", color: "#498ba7" },
	"_c": { c: "\uE00C", color: "#519aba" },
	"_c-sharp_light": { c: "\uE00B", color: "#498ba7" },
	"_c-sharp": { c: "\uE00B", color: "#519aba" },
	"_c_1_light": { c: "\uE00C", color: "#9068b0" },
	"_c_1": { c: "\uE00C", color: "#a074c4" },
	"_c_2_light": { c: "\uE00C", color: "#b7b73b" },
	"_c_2": { c: "\uE00C", color: "#cbcb41" },
	"_cake_light": { c: "\uE00D", color: "#b8383d" },
	"_cake": { c: "\uE00D", color: "#cc3e44" },
	"_cake_php_light": { c: "\uE00E", color: "#b8383d" },
	"_cake_php": { c: "\uE00E", color: "#cc3e44" },
	"_clock_light": { c: "\uE012", color: "#498ba7" },
	"_clock": { c: "\uE012", color: "#519aba" },
	"_clock_1_light": { c: "\uE012", color: "#627379" },
	"_clock_1": { c: "\uE012", color: "#6d8086" },
	"_clojure_light": { c: "\uE013", color: "#7fae42" },
	"_clojure": { c: "\uE013", color: "#8dc149" },
	"_clojure_1_light": { c: "\uE013", color: "#498ba7" },
	"_clojure_1": { c: "\uE013", color: "#519aba" },
	"_code-climate_light": { c: "\uE014", color: "#7fae42" },
	"_code-climate": { c: "\uE014", color: "#8dc149" },
	"_code-search_light": { c: "\uE015", color: "#9068b0" },
	"_code-search": { c: "\uE015", color: "#a074c4" },
	"_coffee_light": { c: "\uE016", color: "#b7b73b" },
	"_coffee": { c: "\uE016", color: "#cbcb41" },
	"_coldfusion_light": { c: "\uE018", color: "#498ba7" },
	"_coldfusion": { c: "\uE018", color: "#519aba" },
	"_config_light": { c: "\uE019", color: "#627379" },
	"_config": { c: "\uE019", color: "#6d8086" },
	"_cpp_light": { c: "\uE01A", color: "#498ba7" },
	"_cpp": { c: "\uE01A", color: "#519aba" },
	"_cpp_1_light": { c: "\uE01A", color: "#9068b0" },
	"_cpp_1": { c: "\uE01A", color: "#a074c4" },
	"_cpp_2_light": { c: "\uE01A", color: "#b7b73b" },
	"_cpp_2": { c: "\uE01A", color: "#cbcb41" },
	"_crystal_light": { c: "\uE01B", color: "#bfc2c1" },
	"_crystal": { c: "\uE01B", color: "#d4d7d6" },
	"_crystal_embedded_light": { c: "\uE01C", color: "#bfc2c1" },
	"_crystal_embedded": { c: "\uE01C", color: "#d4d7d6" },
	"_css_light": { c: "\uE01D", color: "#498ba7" },
	"_css": { c: "\uE01D", color: "#519aba" },
	"_csv_light": { c: "\uE01E", color: "#7fae42" },
	"_csv": { c: "\uE01E", color: "#8dc149" },
	"_cu_light": { c: "\uE01F", color: "#7fae42" },
	"_cu": { c: "\uE01F", color: "#8dc149" },
	"_cu_1_light": { c: "\uE01F", color: "#9068b0" },
	"_cu_1": { c: "\uE01F", color: "#a074c4" },
	"_d_light": { c: "\uE020", color: "#b8383d" },
	"_d": { c: "\uE020", color: "#cc3e44" },
	"_dart_light": { c: "\uE021", color: "#498ba7" },
	"_dart": { c: "\uE021", color: "#519aba" },
	"_db_light": { c: "\uE022", color: "#dd4b78" },
	"_db": { c: "\uE022", color: "#f55385" },
	"_db_1_light": { c: "\uE022", color: "#498ba7" },
	"_db_1": { c: "\uE022", color: "#519aba" },
	"_default_light": { c: "\uE023", color: "#bfc2c1" },
	"_default": { c: "\uE023", color: "#d4d7d6" },
	"_docker_light": { c: "\uE025", color: "#498ba7" },
	"_docker": { c: "\uE025", color: "#519aba" },
	"_docker_1_light": { c: "\uE025", color: "#455155" },
	"_docker_1": { c: "\uE025", color: "#4d5a5e" },
	"_docker_2_light": { c: "\uE025", color: "#7fae42" },
	"_docker_2": { c: "\uE025", color: "#8dc149" },
	"_docker_3_light": { c: "\uE025", color: "#dd4b78" },
	"_docker_3": { c: "\uE025", color: "#f55385" },
	"_ejs_light": { c: "\uE027", color: "#b7b73b" },
	"_ejs": { c: "\uE027", color: "#cbcb41" },
	"_elixir_light": { c: "\uE028", color: "#9068b0" },
	"_elixir": { c: "\uE028", color: "#a074c4" },
	"_elixir_script_light": { c: "\uE029", color: "#9068b0" },
	"_elixir_script": { c: "\uE029", color: "#a074c4" },
	"_elm_light": { c: "\uE02A", color: "#498ba7" },
	"_elm": { c: "\uE02A", color: "#519aba" },
	"_eslint_light": { c: "\uE02C", color: "#9068b0" },
	"_eslint": { c: "\uE02C", color: "#a074c4" },
	"_eslint_1_light": { c: "\uE02C", color: "#455155" },
	"_eslint_1": { c: "\uE02C", color: "#4d5a5e" },
	"_ethereum_light": { c: "\uE02D", color: "#498ba7" },
	"_ethereum": { c: "\uE02D", color: "#519aba" },
	"_f-sharp_light": { c: "\uE02E", color: "#498ba7" },
	"_f-sharp": { c: "\uE02E", color: "#519aba" },
	"_favicon_light": { c: "\uE02F", color: "#b7b73b" },
	"_favicon": { c: "\uE02F", color: "#cbcb41" },
	"_firebase_light": { c: "\uE030", color: "#cc6d2e" },
	"_firebase": { c: "\uE030", color: "#e37933" },
	"_firefox_light": { c: "\uE031", color: "#cc6d2e" },
	"_firefox": { c: "\uE031", color: "#e37933" },
	"_font_light": { c: "\uE033", color: "#b8383d" },
	"_font": { c: "\uE033", color: "#cc3e44" },
	"_git_light": { c: "\uE034", color: "#3b4b52" },
	"_git": { c: "\uE034", color: "#41535b" },
	"_github_light": { c: "\uE037", color: "#bfc2c1" },
	"_github": { c: "\uE037", color: "#d4d7d6" },
	"_gitlab_light": { c: "\uE038", color: "#cc6d2e" },
	"_gitlab": { c: "\uE038", color: "#e37933" },
	"_go_light": { c: "\uE039", color: "#498ba7" },
	"_go": { c: "\uE039", color: "#519aba" },
	"_go2_light": { c: "\uE03A", color: "#498ba7" },
	"_go2": { c: "\uE03A", color: "#519aba" },
	"_godot_light": { c: "\uE03B", color: "#498ba7" },
	"_godot": { c: "\uE03B", color: "#519aba" },
	"_godot_1_light": { c: "\uE03B", color: "#b8383d" },
	"_godot_1": { c: "\uE03B", color: "#cc3e44" },
	"_godot_2_light": { c: "\uE03B", color: "#b7b73b" },
	"_godot_2": { c: "\uE03B", color: "#cbcb41" },
	"_godot_3_light": { c: "\uE03B", color: "#9068b0" },
	"_godot_3": { c: "\uE03B", color: "#a074c4" },
	"_gradle_light": { c: "\uE03C", color: "#498ba7" },
	"_gradle": { c: "\uE03C", color: "#519aba" },
	"_grails_light": { c: "\uE03D", color: "#7fae42" },
	"_grails": { c: "\uE03D", color: "#8dc149" },
	"_graphql_light": { c: "\uE03E", color: "#dd4b78" },
	"_graphql": { c: "\uE03E", color: "#f55385" },
	"_grunt_light": { c: "\uE03F", color: "#cc6d2e" },
	"_grunt": { c: "\uE03F", color: "#e37933" },
	"_gulp_light": { c: "\uE040", color: "#b8383d" },
	"_gulp": { c: "\uE040", color: "#cc3e44" },
	"_hacklang_light": { c: "\uE041", color: "#cc6d2e" },
	"_hacklang": { c: "\uE041", color: "#e37933" },
	"_haml_light": { c: "\uE042", color: "#b8383d" },
	"_haml": { c: "\uE042", color: "#cc3e44" },
	"_happenings_light": { c: "\uE043", color: "#498ba7" },
	"_happenings": { c: "\uE043", color: "#519aba" },
	"_haskell_light": { c: "\uE044", color: "#9068b0" },
	"_haskell": { c: "\uE044", color: "#a074c4" },
	"_haxe_light": { c: "\uE045", color: "#cc6d2e" },
	"_haxe": { c: "\uE045", color: "#e37933" },
	"_haxe_1_light": { c: "\uE045", color: "#b7b73b" },
	"_haxe_1": { c: "\uE045", color: "#cbcb41" },
	"_haxe_2_light": { c: "\uE045", color: "#498ba7" },
	"_haxe_2": { c: "\uE045", color: "#519aba" },
	"_haxe_3_light": { c: "\uE045", color: "#9068b0" },
	"_haxe_3": { c: "\uE045", color: "#a074c4" },
	"_heroku_light": { c: "\uE046", color: "#9068b0" },
	"_heroku": { c: "\uE046", color: "#a074c4" },
	"_hex_light": { c: "\uE047", color: "#b8383d" },
	"_hex": { c: "\uE047", color: "#cc3e44" },
	"_html_light": { c: "\uE048", color: "#498ba7" },
	"_html": { c: "\uE048", color: "#519aba" },
	"_html_1_light": { c: "\uE048", color: "#7fae42" },
	"_html_1": { c: "\uE048", color: "#8dc149" },
	"_html_2_light": { c: "\uE048", color: "#b7b73b" },
	"_html_2": { c: "\uE048", color: "#cbcb41" },
	"_html_3_light": { c: "\uE048", color: "#cc6d2e" },
	"_html_3": { c: "\uE048", color: "#e37933" },
	"_html_erb_light": { c: "\uE049", color: "#b8383d" },
	"_html_erb": { c: "\uE049", color: "#cc3e44" },
	"_ignored_light": { c: "\uE04A", color: "#3b4b52" },
	"_ignored": { c: "\uE04A", color: "#41535b" },
	"_illustrator_light": { c: "\uE04B", color: "#b7b73b" },
	"_illustrator": { c: "\uE04B", color: "#cbcb41" },
	"_image_light": { c: "\uE04C", color: "#9068b0" },
	"_image": { c: "\uE04C", color: "#a074c4" },
	"_info_light": { c: "\uE04D", color: "#498ba7" },
	"_info": { c: "\uE04D", color: "#519aba" },
	"_ionic_light": { c: "\uE04E", color: "#498ba7" },
	"_ionic": { c: "\uE04E", color: "#519aba" },
	"_jade_light": { c: "\uE04F", color: "#b8383d" },
	"_jade": { c: "\uE04F", color: "#cc3e44" },
	"_java_light": { c: "\uE050", color: "#b8383d" },
	"_java": { c: "\uE050", color: "#cc3e44" },
	"_java_1_light": { c: "\uE050", color: "#498ba7" },
	"_java_1": { c: "\uE050", color: "#519aba" },
	"_javascript_light": { c: "\uE051", color: "#b7b73b" },
	"_javascript": { c: "\uE051", color: "#cbcb41" },
	"_javascript_1_light": { c: "\uE051", color: "#cc6d2e" },
	"_javascript_1": { c: "\uE051", color: "#e37933" },
	"_javascript_2_light": { c: "\uE051", color: "#498ba7" },
	"_javascript_2": { c: "\uE051", color: "#519aba" },
	"_jenkins_light": { c: "\uE052", color: "#b8383d" },
	"_jenkins": { c: "\uE052", color: "#cc3e44" },
	"_jinja_light": { c: "\uE053", color: "#b8383d" },
	"_jinja": { c: "\uE053", color: "#cc3e44" },
	"_json_light": { c: "\uE055", color: "#b7b73b" },
	"_json": { c: "\uE055", color: "#cbcb41" },
	"_json_1_light": { c: "\uE055", color: "#7fae42" },
	"_json_1": { c: "\uE055", color: "#8dc149" },
	"_julia_light": { c: "\uE056", color: "#9068b0" },
	"_julia": { c: "\uE056", color: "#a074c4" },
	"_karma_light": { c: "\uE057", color: "#7fae42" },
	"_karma": { c: "\uE057", color: "#8dc149" },
	"_kotlin_light": { c: "\uE058", color: "#cc6d2e" },
	"_kotlin": { c: "\uE058", color: "#e37933" },
	"_less_light": { c: "\uE059", color: "#498ba7" },
	"_less": { c: "\uE059", color: "#519aba" },
	"_license_light": { c: "\uE05A", color: "#b7b73b" },
	"_license": { c: "\uE05A", color: "#cbcb41" },
	"_license_1_light": { c: "\uE05A", color: "#cc6d2e" },
	"_license_1": { c: "\uE05A", color: "#e37933" },
	"_license_2_light": { c: "\uE05A", color: "#b8383d" },
	"_license_2": { c: "\uE05A", color: "#cc3e44" },
	"_liquid_light": { c: "\uE05B", color: "#7fae42" },
	"_liquid": { c: "\uE05B", color: "#8dc149" },
	"_livescript_light": { c: "\uE05C", color: "#498ba7" },
	"_livescript": { c: "\uE05C", color: "#519aba" },
	"_lock_light": { c: "\uE05D", color: "#7fae42" },
	"_lock": { c: "\uE05D", color: "#8dc149" },
	"_lua_light": { c: "\uE05E", color: "#498ba7" },
	"_lua": { c: "\uE05E", color: "#519aba" },
	"_makefile_light": { c: "\uE05F", color: "#cc6d2e" },
	"_makefile": { c: "\uE05F", color: "#e37933" },
	"_makefile_1_light": { c: "\uE05F", color: "#9068b0" },
	"_makefile_1": { c: "\uE05F", color: "#a074c4" },
	"_makefile_2_light": { c: "\uE05F", color: "#627379" },
	"_makefile_2": { c: "\uE05F", color: "#6d8086" },
	"_makefile_3_light": { c: "\uE05F", color: "#498ba7" },
	"_makefile_3": { c: "\uE05F", color: "#519aba" },
	"_markdown_light": { c: "\uE060", color: "#498ba7" },
	"_markdown": { c: "\uE060", color: "#519aba" },
	"_maven_light": { c: "\uE061", color: "#b8383d" },
	"_maven": { c: "\uE061", color: "#cc3e44" },
	"_mdo_light": { c: "\uE062", color: "#b8383d" },
	"_mdo": { c: "\uE062", color: "#cc3e44" },
	"_mustache_light": { c: "\uE063", color: "#cc6d2e" },
	"_mustache": { c: "\uE063", color: "#e37933" },
	"_nim_light": { c: "\uE065", color: "#b7b73b" },
	"_nim": { c: "\uE065", color: "#cbcb41" },
	"_notebook_light": { c: "\uE066", color: "#498ba7" },
	"_notebook": { c: "\uE066", color: "#519aba" },
	"_npm_light": { c: "\uE067", color: "#3b4b52" },
	"_npm": { c: "\uE067", color: "#41535b" },
	"_npm_1_light": { c: "\uE067", color: "#b8383d" },
	"_npm_1": { c: "\uE067", color: "#cc3e44" },
	"_npm_ignored_light": { c: "\uE068", color: "#3b4b52" },
	"_npm_ignored": { c: "\uE068", color: "#41535b" },
	"_nunjucks_light": { c: "\uE069", color: "#7fae42" },
	"_nunjucks": { c: "\uE069", color: "#8dc149" },
	"_ocaml_light": { c: "\uE06A", color: "#cc6d2e" },
	"_ocaml": { c: "\uE06A", color: "#e37933" },
	"_odata_light": { c: "\uE06B", color: "#cc6d2e" },
	"_odata": { c: "\uE06B", color: "#e37933" },
	"_pddl_light": { c: "\uE06C", color: "#9068b0" },
	"_pddl": { c: "\uE06C", color: "#a074c4" },
	"_pdf_light": { c: "\uE06D", color: "#b8383d" },
	"_pdf": { c: "\uE06D", color: "#cc3e44" },
	"_perl_light": { c: "\uE06E", color: "#498ba7" },
	"_perl": { c: "\uE06E", color: "#519aba" },
	"_photoshop_light": { c: "\uE06F", color: "#498ba7" },
	"_photoshop": { c: "\uE06F", color: "#519aba" },
	"_php_light": { c: "\uE070", color: "#9068b0" },
	"_php": { c: "\uE070", color: "#a074c4" },
	"_pipeline_light": { c: "\uE071", color: "#cc6d2e" },
	"_pipeline": { c: "\uE071", color: "#e37933" },
	"_plan_light": { c: "\uE072", color: "#7fae42" },
	"_plan": { c: "\uE072", color: "#8dc149" },
	"_platformio_light": { c: "\uE073", color: "#cc6d2e" },
	"_platformio": { c: "\uE073", color: "#e37933" },
	"_powershell_light": { c: "\uE074", color: "#498ba7" },
	"_powershell": { c: "\uE074", color: "#519aba" },
	"_prisma_light": { c: "\uE075", color: "#498ba7" },
	"_prisma": { c: "\uE075", color: "#519aba" },
	"_prolog_light": { c: "\uE077", color: "#cc6d2e" },
	"_prolog": { c: "\uE077", color: "#e37933" },
	"_pug_light": { c: "\uE078", color: "#b8383d" },
	"_pug": { c: "\uE078", color: "#cc3e44" },
	"_puppet_light": { c: "\uE079", color: "#b7b73b" },
	"_puppet": { c: "\uE079", color: "#cbcb41" },
	"_purescript_light": { c: "\uE07A", color: "#bfc2c1" },
	"_purescript": { c: "\uE07A", color: "#d4d7d6" },
	"_python_light": { c: "\uE07B", color: "#498ba7" },
	"_python": { c: "\uE07B", color: "#519aba" },
	"_react_light": { c: "\uE07D", color: "#498ba7" },
	"_react": { c: "\uE07D", color: "#519aba" },
	"_react_1_light": { c: "\uE07D", color: "#cc6d2e" },
	"_react_1": { c: "\uE07D", color: "#e37933" },
	"_reasonml_light": { c: "\uE07E", color: "#b8383d" },
	"_reasonml": { c: "\uE07E", color: "#cc3e44" },
	"_rescript_light": { c: "\uE07F", color: "#b8383d" },
	"_rescript": { c: "\uE07F", color: "#cc3e44" },
	"_rescript_1_light": { c: "\uE07F", color: "#dd4b78" },
	"_rescript_1": { c: "\uE07F", color: "#f55385" },
	"_rollup_light": { c: "\uE080", color: "#b8383d" },
	"_rollup": { c: "\uE080", color: "#cc3e44" },
	"_ruby_light": { c: "\uE081", color: "#b8383d" },
	"_ruby": { c: "\uE081", color: "#cc3e44" },
	"_rust_light": { c: "\uE082", color: "#627379" },
	"_rust": { c: "\uE082", color: "#6d8086" },
	"_salesforce_light": { c: "\uE083", color: "#498ba7" },
	"_salesforce": { c: "\uE083", color: "#519aba" },
	"_sass_light": { c: "\uE084", color: "#dd4b78" },
	"_sass": { c: "\uE084", color: "#f55385" },
	"_sbt_light": { c: "\uE085", color: "#498ba7" },
	"_sbt": { c: "\uE085", color: "#519aba" },
	"_scala_light": { c: "\uE086", color: "#b8383d" },
	"_scala": { c: "\uE086", color: "#cc3e44" },
	"_shell_light": { c: "\uE089", color: "#7fae42" },
	"_shell": { c: "\uE089", color: "#8dc149" },
	"_slim_light": { c: "\uE08A", color: "#cc6d2e" },
	"_slim": { c: "\uE08A", color: "#e37933" },
	"_smarty_light": { c: "\uE08B", color: "#b7b73b" },
	"_smarty": { c: "\uE08B", color: "#cbcb41" },
	"_spring_light": { c: "\uE08C", color: "#7fae42" },
	"_spring": { c: "\uE08C", color: "#8dc149" },
	"_stylelint_light": { c: "\uE08D", color: "#bfc2c1" },
	"_stylelint": { c: "\uE08D", color: "#d4d7d6" },
	"_stylelint_1_light": { c: "\uE08D", color: "#455155" },
	"_stylelint_1": { c: "\uE08D", color: "#4d5a5e" },
	"_stylus_light": { c: "\uE08E", color: "#7fae42" },
	"_stylus": { c: "\uE08E", color: "#8dc149" },
	"_sublime_light": { c: "\uE08F", color: "#cc6d2e" },
	"_sublime": { c: "\uE08F", color: "#e37933" },
	"_svelte_light": { c: "\uE090", color: "#b8383d" },
	"_svelte": { c: "\uE090", color: "#cc3e44" },
	"_svg_light": { c: "\uE091", color: "#9068b0" },
	"_svg": { c: "\uE091", color: "#a074c4" },
	"_svg_1_light": { c: "\uE091", color: "#498ba7" },
	"_svg_1": { c: "\uE091", color: "#519aba" },
	"_swift_light": { c: "\uE092", color: "#cc6d2e" },
	"_swift": { c: "\uE092", color: "#e37933" },
	"_terraform_light": { c: "\uE093", color: "#9068b0" },
	"_terraform": { c: "\uE093", color: "#a074c4" },
	"_tex_light": { c: "\uE094", color: "#498ba7" },
	"_tex": { c: "\uE094", color: "#519aba" },
	"_tex_1_light": { c: "\uE094", color: "#b7b73b" },
	"_tex_1": { c: "\uE094", color: "#cbcb41" },
	"_tex_2_light": { c: "\uE094", color: "#cc6d2e" },
	"_tex_2": { c: "\uE094", color: "#e37933" },
	"_tex_3_light": { c: "\uE094", color: "#bfc2c1" },
	"_tex_3": { c: "\uE094", color: "#d4d7d6" },
	"_todo": { c: "\uE096", color: "undefined" },
	"_tsconfig_light": { c: "\uE097", color: "#498ba7" },
	"_tsconfig": { c: "\uE097", color: "#519aba" },
	"_twig_light": { c: "\uE098", color: "#7fae42" },
	"_twig": { c: "\uE098", color: "#8dc149" },
	"_typescript_light": { c: "\uE099", color: "#498ba7" },
	"_typescript": { c: "\uE099", color: "#519aba" },
	"_typescript_1_light": { c: "\uE099", color: "#cc6d2e" },
	"_typescript_1": { c: "\uE099", color: "#e37933" },
	"_vala_light": { c: "\uE09A", color: "#627379" },
	"_vala": { c: "\uE09A", color: "#6d8086" },
	"_video_light": { c: "\uE09B", color: "#dd4b78" },
	"_video": { c: "\uE09B", color: "#f55385" },
	"_vite_light": { c: "\uE09C", color: "#b7b73b" },
	"_vite": { c: "\uE09C", color: "#cbcb41" },
	"_vue_light": { c: "\uE09D", color: "#7fae42" },
	"_vue": { c: "\uE09D", color: "#8dc149" },
	"_wasm_light": { c: "\uE09E", color: "#9068b0" },
	"_wasm": { c: "\uE09E", color: "#a074c4" },
	"_wat_light": { c: "\uE09F", color: "#9068b0" },
	"_wat": { c: "\uE09F", color: "#a074c4" },
	"_webpack_light": { c: "\uE0A0", color: "#498ba7" },
	"_webpack": { c: "\uE0A0", color: "#519aba" },
	"_wgt_light": { c: "\uE0A1", color: "#498ba7" },
	"_wgt": { c: "\uE0A1", color: "#519aba" },
	"_windows_light": { c: "\uE0A2", color: "#498ba7" },
	"_windows": { c: "\uE0A2", color: "#519aba" },
	"_word_light": { c: "\uE0A3", color: "#498ba7" },
	"_word": { c: "\uE0A3", color: "#519aba" },
	"_xls_light": { c: "\uE0A4", color: "#7fae42" },
	"_xls": { c: "\uE0A4", color: "#8dc149" },
	"_xml_light": { c: "\uE0A5", color: "#cc6d2e" },
	"_xml": { c: "\uE0A5", color: "#e37933" },
	"_yarn_light": { c: "\uE0A6", color: "#498ba7" },
	"_yarn": { c: "\uE0A6", color: "#519aba" },
	"_yml_light": { c: "\uE0A7", color: "#9068b0" },
	"_yml": { c: "\uE0A7", color: "#a074c4" },
	"_zig_light": { c: "\uE0A8", color: "#cc6d2e" },
	"_zig": { c: "\uE0A8", color: "#e37933" },
	"_zip_light": { c: "\uE0A9", color: "#b8383d" },
	"_zip": { c: "\uE0A9", color: "#cc3e44" },
	"_zip_1_light": { c: "\uE0A9", color: "#627379" },
	"_zip_1": { c: "\uE0A9", color: "#6d8086" },
};

export const DEFAULT_FILE = "_default";

export const FILENAMES: Record<string, string> = {
	"mix": "_hex",
	"karma.conf.js": "_karma",
	"karma.conf.cjs": "_karma",
	"karma.conf.mjs": "_karma",
	"karma.conf.coffee": "_karma",
	"readme.md": "_info",
	"readme.txt": "_info",
	"readme": "_info",
	"changelog.md": "_clock",
	"changelog.txt": "_clock",
	"changelog": "_clock",
	"changes.md": "_clock",
	"changes.txt": "_clock",
	"changes": "_clock",
	"version.md": "_clock",
	"version.txt": "_clock",
	"version": "_clock",
	"mvnw": "_maven",
	"pom.xml": "_maven",
	"tsconfig.json": "_tsconfig",
	"vite.config.js": "_vite",
	"vite.config.ts": "_vite",
	"vite.config.mjs": "_vite",
	"vite.config.mts": "_vite",
	"vite.config.cjs": "_vite",
	"vite.config.cts": "_vite",
	"swagger.json": "_json_1",
	"swagger.yml": "_json_1",
	"swagger.yaml": "_json_1",
	"mime.types": "_config",
	"jenkinsfile": "_jenkins",
	"babel.config.js": "_babel",
	"babel.config.json": "_babel",
	"babel.config.cjs": "_babel",
	"build": "_bazel",
	"build.bazel": "_bazel",
	"workspace": "_bazel",
	"workspace.bazel": "_bazel",
	"bower.json": "_bower",
	"docker-healthcheck": "_docker_2",
	"eslint.config.js": "_eslint",
	"firebase.json": "_firebase",
	"geckodriver": "_firefox",
	"gruntfile.js": "_grunt",
	"gruntfile.babel.js": "_grunt",
	"gruntfile.coffee": "_grunt",
	"gulpfile": "_gulp",
	"gulpfile.js": "_gulp",
	"ionic.config.json": "_ionic",
	"ionic.project": "_ionic",
	"platformio.ini": "_platformio",
	"rollup.config.js": "_rollup",
	"sass-lint.yml": "_sass",
	"stylelint.config.js": "_stylelint",
	"stylelint.config.cjs": "_stylelint",
	"stylelint.config.mjs": "_stylelint",
	"yarn.clean": "_yarn",
	"yarn.lock": "_yarn",
	"webpack.config.js": "_webpack",
	"webpack.config.cjs": "_webpack",
	"webpack.config.mjs": "_webpack",
	"webpack.config.ts": "_webpack",
	"webpack.config.build.js": "_webpack",
	"webpack.config.build.cjs": "_webpack",
	"webpack.config.build.mjs": "_webpack",
	"webpack.config.build.ts": "_webpack",
	"webpack.common.js": "_webpack",
	"webpack.common.cjs": "_webpack",
	"webpack.common.mjs": "_webpack",
	"webpack.common.ts": "_webpack",
	"webpack.dev.js": "_webpack",
	"webpack.dev.cjs": "_webpack",
	"webpack.dev.mjs": "_webpack",
	"webpack.dev.ts": "_webpack",
	"webpack.prod.js": "_webpack",
	"webpack.prod.cjs": "_webpack",
	"webpack.prod.mjs": "_webpack",
	"webpack.prod.ts": "_webpack",
	"license": "_license",
	"licence": "_license",
	"license.txt": "_license",
	"licence.txt": "_license",
	"license.md": "_license",
	"licence.md": "_license",
	"copying": "_license",
	"copying.txt": "_license",
	"copying.md": "_license",
	"compiling": "_license_1",
	"compiling.txt": "_license_1",
	"compiling.md": "_license_1",
	"contributing": "_license_2",
	"contributing.txt": "_license_2",
	"contributing.md": "_license_2",
	"qmakefile": "_makefile_1",
	"omakefile": "_makefile_2",
	"cmakelists.txt": "_makefile_3",
	"procfile": "_heroku",
	"todo": "_todo",
	"todo.txt": "_todo",
	"todo.md": "_todo",
	"npm-debug.log": "_npm_ignored",
};

export const EXTENSIONS: Record<string, string> = {
	"bsl": "_bsl",
	"mdo": "_mdo",
	"cls": "_salesforce",
	"apex": "_salesforce",
	"asm": "_asm",
	"s": "_asm",
	"bicep": "_bicep",
	"bzl": "_bazel",
	"bazel": "_bazel",
	"build": "_bazel",
	"workspace": "_bazel",
	"bazelignore": "_bazel",
	"bazelversion": "_bazel",
	"h": "_c_1",
	"aspx": "_html",
	"ascx": "_html_1",
	"asax": "_html_2",
	"master": "_html_2",
	"hh": "_cpp_1",
	"hpp": "_cpp_1",
	"hxx": "_cpp_1",
	"h++": "_cpp_1",
	"edn": "_clojure_1",
	"cfc": "_coldfusion",
	"cfm": "_coldfusion",
	"litcoffee": "_coffee",
	"config": "_config",
	"cr": "_crystal",
	"ecr": "_crystal_embedded",
	"slang": "_crystal_embedded",
	"cson": "_json",
	"css.map": "_css",
	"sss": "_css",
	"csv": "_csv",
	"xls": "_xls",
	"xlsx": "_xls",
	"cuh": "_cu_1",
	"hu": "_cu_1",
	"cake": "_cake",
	"ctp": "_cake_php",
	"d": "_d",
	"doc": "_word",
	"docx": "_word",
	"ejs": "_ejs",
	"ex": "_elixir",
	"exs": "_elixir_script",
	"elm": "_elm",
	"ico": "_favicon",
	"gitconfig": "_git",
	"gitkeep": "_git",
	"gitattributes": "_git",
	"gitmodules": "_git",
	"slide": "_go",
	"article": "_go",
	"gd": "_godot",
	"godot": "_godot_1",
	"tres": "_godot_2",
	"tscn": "_godot_3",
	"gradle": "_gradle",
	"gsp": "_grails",
	"gql": "_graphql",
	"graphql": "_graphql",
	"graphqls": "_graphql",
	"hack": "_hacklang",
	"haml": "_haml",
	"hs": "_haskell",
	"lhs": "_haskell",
	"hx": "_haxe",
	"hxs": "_haxe_1",
	"hxp": "_haxe_2",
	"hxml": "_haxe_3",
	"jade": "_jade",
	"class": "_java_1",
	"classpath": "_java",
	"js.map": "_javascript",
	"cjs.map": "_javascript",
	"mjs.map": "_javascript",
	"spec.js": "_javascript_1",
	"spec.cjs": "_javascript_1",
	"spec.mjs": "_javascript_1",
	"test.js": "_javascript_1",
	"test.cjs": "_javascript_1",
	"test.mjs": "_javascript_1",
	"es": "_javascript",
	"es5": "_javascript",
	"es7": "_javascript",
	"jinja": "_jinja",
	"jinja2": "_jinja",
	"kt": "_kotlin",
	"kts": "_kotlin",
	"liquid": "_liquid",
	"ls": "_livescript",
	"argdown": "_argdown",
	"ad": "_argdown",
	"mustache": "_mustache",
	"stache": "_mustache",
	"nim": "_nim",
	"nims": "_nim",
	"github-issues": "_github",
	"ipynb": "_notebook",
	"njk": "_nunjucks",
	"nunjucks": "_nunjucks",
	"nunjs": "_nunjucks",
	"nunj": "_nunjucks",
	"njs": "_nunjucks",
	"nj": "_nunjucks",
	"npm-debug.log": "_npm",
	"npmignore": "_npm_1",
	"npmrc": "_npm_1",
	"ml": "_ocaml",
	"mli": "_ocaml",
	"cmx": "_ocaml",
	"cmxa": "_ocaml",
	"odata": "_odata",
	"php.inc": "_php",
	"pipeline": "_pipeline",
	"pddl": "_pddl",
	"plan": "_plan",
	"happenings": "_happenings",
	"prisma": "_prisma",
	"pp": "_puppet",
	"epp": "_puppet",
	"purs": "_purescript",
	"spec.jsx": "_react_1",
	"test.jsx": "_react_1",
	"cjsx": "_react",
	"spec.tsx": "_react_1",
	"test.tsx": "_react_1",
	"re": "_reasonml",
	"res": "_rescript",
	"resi": "_rescript_1",
	"r": "_R",
	"rmd": "_R",
	"erb": "_html_erb",
	"erb.html": "_html_erb",
	"html.erb": "_html_erb",
	"sass": "_sass",
	"springbeans": "_spring",
	"slim": "_slim",
	"smarty.tpl": "_smarty",
	"tpl": "_smarty",
	"sbt": "_sbt",
	"scala": "_scala",
	"sol": "_ethereum",
	"styl": "_stylus",
	"svelte": "_svelte",
	"soql": "_db_1",
	"tf": "_terraform",
	"tf.json": "_terraform",
	"tfvars": "_terraform",
	"tfvars.json": "_terraform",
	"dtx": "_tex_2",
	"ins": "_tex_3",
	"toml": "_config",
	"twig": "_twig",
	"spec.ts": "_typescript_1",
	"test.ts": "_typescript_1",
	"vala": "_vala",
	"vapi": "_vala",
	"component": "_html_3",
	"vue": "_vue",
	"wasm": "_wasm",
	"wat": "_wat",
	"pro": "_prolog",
	"zig": "_zig",
	"jar": "_zip",
	"zip": "_zip_1",
	"wgt": "_wgt",
	"ai": "_illustrator",
	"psd": "_photoshop",
	"pdf": "_pdf",
	"eot": "_font",
	"ttf": "_font",
	"woff": "_font",
	"woff2": "_font",
	"otf": "_font",
	"avif": "_image",
	"gif": "_image",
	"jpg": "_image",
	"jpeg": "_image",
	"png": "_image",
	"pxm": "_image",
	"svg": "_svg",
	"svgx": "_image",
	"tiff": "_image",
	"webp": "_image",
	"sublime-project": "_sublime",
	"sublime-workspace": "_sublime",
	"mov": "_video",
	"ogv": "_video",
	"webm": "_video",
	"avi": "_video",
	"mpg": "_video",
	"mp4": "_video",
	"mp3": "_audio",
	"ogg": "_audio",
	"wav": "_audio",
	"flac": "_audio",
	"3ds": "_svg_1",
	"3dm": "_svg_1",
	"stl": "_svg_1",
	"obj": "_svg_1",
	"dae": "_svg_1",
	"babelrc": "_babel",
	"babelrc.js": "_babel",
	"babelrc.cjs": "_babel",
	"bazelrc": "_bazel_1",
	"bowerrc": "_bower",
	"dockerignore": "_docker_1",
	"codeclimate.yml": "_code-climate",
	"eslintrc": "_eslint",
	"eslintrc.js": "_eslint",
	"eslintrc.cjs": "_eslint",
	"eslintrc.yaml": "_eslint",
	"eslintrc.yml": "_eslint",
	"eslintrc.json": "_eslint",
	"eslintignore": "_eslint_1",
	"firebaserc": "_firebase",
	"gitlab-ci.yml": "_gitlab",
	"jshintrc": "_javascript_2",
	"jscsrc": "_javascript_2",
	"stylelintrc": "_stylelint",
	"stylelintrc.json": "_stylelint",
	"stylelintrc.yaml": "_stylelint",
	"stylelintrc.yml": "_stylelint",
	"stylelintrc.js": "_stylelint",
	"stylelintignore": "_stylelint_1",
	"direnv": "_config",
	"static": "_config",
	"slugignore": "_config",
	"tmp": "_clock_1",
	"htaccess": "_config",
	"key": "_lock",
	"cert": "_lock",
	"cer": "_lock",
	"crt": "_lock",
	"pem": "_lock",
	"ds_store": "_ignored",
};

export type IconSpec = { c: string; color: string };

function icon(name: string): IconSpec {
  return ICONS[name] ?? ICONS[DEFAULT_FILE] ?? { c: "\uE000", color: "#9ca3af" };
}

/** VSCode matching order: exact filename (lowercased, leading dot stripped),
 * then the longest dot-suffix ("spec.ts" before "ts"), then the plain file. */
export function fileIconFor(basename: string): IconSpec {
  const name = basename.toLowerCase().replace(/^\./, "");
  const byName = FILENAMES[name];
  if (byName) return icon(byName);
  // Extension candidates: the full name first (catches dotted rules like
  // "npm-debug.log" / "css.map"), then ever-shorter suffixes.
  const parts = name.split(".");
  for (let i = 0; i < parts.length; i++) {
    const cand = parts.slice(i).join(".");
    const byExt = EXTENSIONS[cand];
    if (byExt) return icon(byExt);
  }
  return icon(DEFAULT_FILE);
}
